### ISSUE TITLE
Fast switching of channel names 

### ISSUE THREAD

**Issue by borondics** [biolab/orange-canvas-core#134]
This has been a visual enhancement I've been contemplating for quite some time now, so I'll ask here because there are some visual improvements in progress, like #133. 

The channel names display is a very useful and important feature to know if the right inputs/outputs are connected.

However, especially with large workflows (and I mean LARGE with dozens of widgets) having the text over the widget connectors can be very messy and visually distracting. 

So I wonder if it would be a good improvement to have no channel names as default and adding a shortcut key, which upon keypress would either toggle the names or simply show them for the duration of the keypress? @irgolic, what do you think of this as a visual improvement?

**Comment by irgolic** [comment]
Would #129 satisfy your needs?
