### ISSUE TITLE
Windows not listed in Window menu

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange-canvas-core#163]
- [ ] **What's wrong?**

I assume that this is not intentional:  In all other Mac applications the Window menu lists all the open windows in the application, so that one can choose one to bring to the front, but Orange only has the options Minimize and Zoom.

- [ ] **How can we reproduce the problem?** 

Create some workflows with File→New, then select Window.  It should (in my opinion) list the workflow windows just created.  it does not.

- [ ] **What's your environment?**

- Operating system: macOS 11.1
- Orange version: 3.27.1
- How you installed Orange: Disk image downloaded from https://download.biolab.si/download/files/Orange3-3.27.1-Python3.7.6.dmg

**Comment by irgolic** [comment]
You're right, thanks.

Whoever takes a stab at this should also list the windows in the menu that pops up when right-clicking the app in Mac's dock.

**Comment by janezd** [comment]
Fixed.
