### ISSUE TITLE
Connecting backwards does not work

### ISSUE THREAD

**Issue by janezd** [biolab/orange-canvas-core#165]
https://user-images.githubusercontent.com/2387315/104712493-e6f12500-5722-11eb-9b94-c1f3870031f1.mov

I believe this is related to #154. :(

**Comment by irgolic** [comment]
I can't replicate this. Can you make a step-by-step guide, including keystrokes?

**Comment by janezd** [comment]
I was apparently on some outdated branch. Sorry about that.
