### ISSUE TITLE
Ugly text on widget links in Windows

### ISSUE THREAD

**Issue by andraz213** [biolab/orange-canvas-core#182]
The "Selected Data -> Data" text is broken in many ways.

![Posnetek zaslona 2021-03-26 085803](https://user-images.githubusercontent.com/36739449/112600417-77c63a00-8e11-11eb-8f05-ab36503806a2.png)

OS: Windows10
Orange version: 3.28.0

**Comment by ales-erjavec** [comment]
This is caused by https://bugreports.qt.io/browse/QTBUG-21377
