### ISSUE TITLE
[RFC] Making visible channels on widget achors the default

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-canvas-core#214]
gh-154 introduced making widget channels explicit when you mouseover AND hold shift.

I love it. Makes some workflows so much easier to build. It also enhances discoverability for new users. And it is beautifully executed, thanks again, @irgolic.

At the time we discussed it, someone mentioned that having this as default could confuse new users. I agree. It definitely could confuse confused users, but I strongly believe that it is better to make confusion explicit.

**Comment by janezd** [comment]
We add a setting that enables this without pressing ShiFt,
