### ISSUE TITLE
Output/input subtypes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#230]
We are struggling quite a bit with widget signals in Text. Currently, widgets look at signal type (Table, Corpus, Distances, etc.) and take the first suitable input. However, we'd often like to be more specific.
I.e. Ontology outputs Words, which is a Table. Connecting it to Semantic Viewer first, results in Words being used as a Corpus instead of Words.
<img width="287" alt="Screenshot 2022-05-09 at 11 03 20" src="https://user-images.githubusercontent.com/12524972/167377211-d057cc7f-ab43-45e3-ae08-9161c3fde371.png">

Preferably, one could define a more specific input type, so when Words are on the input, they would be used as Words, not Corpus. This would currently be most useful for Text, but surely there could be other use cases.

**Comment by ales-erjavec** [comment]
If https://github.com/biolab/orange3-text/pull/855 is not sufficient then reopen this.
