### ISSUE TITLE
Cannot get widget description from module

### ISSUE THREAD

**Issue by woutdenolf** [biolab/orange-canvas-core#232]
It seems widgets cannot be loaded when using `python -m orangecanvas` while they can be loaded if you have a full orange installation with `python -m Orange.canvas`.

Looking at the code I noticed that extracting the widget description from a module is done in orange-canvas-core like this

https://github.com/biolab/orange-canvas-core/blob/7c87f68b569bb8a3c3c36dd0a72403bcd35bb633/orangecanvas/registry/utils.py#L16-L20

and when you have have orange it is done like this

https://github.com/biolab/orange-widget-base/blob/dd3e3eab3b040ef5f57125847093c6d701450e1c/orangewidget/workflow/discovery.py#L5-L10

Is there a reason for this difference?

In addition we have two entry points `orange.widgets` and `orangecanvas.widgets`. Does this mean if I have an addon that should work for both, I have to register my project with both?

**Comment by woutdenolf** [comment]
ping @payno

**Comment by ales-erjavec** [comment]
> It seems widgets cannot be loaded when using python -m orangecanvas while they can be loaded if you have a full orange installation with python -m Orange.canvas.

Yes. Although you can run `python -m orangecanvas --config Orange.canvas.config.Config` to load the same set of widgets, but there will be some regression in functionality.
 

> Looking at the code I noticed that extracting the widget description from a module is done in orange-canvas-core like this
> 
> https://github.com/biolab/orange-canvas-core/blob/7c87f68b569bb8a3c3c36dd0a72403bcd35bb633/orangecanvas/registry/utils.py#L16-L20
> and when you have have orange it is done like this
> 
> https://github.com/biolab/orange-widget-base/blob/dd3e3eab3b040ef5f57125847093c6d701450e1c/orangewidget/workflow/discovery.py#L5-L10
>
> Is there a reason for this difference?

The one here is only for legacy (and testing) reasons.

> In addition we have two entry points orange.widgets and orangecanvas.widgets. Does this mean if I have an addon that should work for both, I have to register my project with both?

The default configuration for `orangecanvas.widgets` does not define a full execution model. You cannot have a node that works for both.

**Comment by woutdenolf** [comment]
So if I understand correctly `python -m orangecanvas` does not have any real usage and there is no use in add a project to the `orangecanvas.widgets` entry point group?

**Comment by markotoplak** [comment]
@woutdenolf, could you describe your use case a bit? If I understand correctly, you are running canvas-core directly.

Perhaps making a thin wrapper around orange-canvas-core that changes the initialization could be a solution.
