### ISSUE TITLE
Widget search

### ISSUE THREAD

**Issue by simonaubertbd** [biolab/orange-canvas-core#273]
Hello all,

A small quick-win : I noticed the widgets are not alphabetically ordered. I understand this may be to get the most used at first (or maybe something like that). However this means I loose time to find the correct widget I want to use.

So, what I propose is a "search" space over or at the beginning of the widget list.

Best regards,

Simon

**Comment by simonaubertbd** [comment]
sorry, in the wrong space

**Comment by markotoplak** [comment]
@simonaubertbd, if you know what you are looking for I suggest double clicking the canvas and typing it in. For advanced users I often suggest that they hide the left pane.

And yes, they are intentionally ordered differently.
