### ISSUE TITLE
Release 0.2.0 bug: get project name from entree point

### ISSUE THREAD

**Issue by woutdenolf** [biolab/orange-canvas-core#292]
```
2023-12-15 13:45:42,261:ERROR:orangecanvas.registry.discovery: An exception occurred while processing EntryPoint.parse('Ewoks Demo = orangecontrib.ewoksdemo').
Traceback (most recent call last):
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/orangecanvas/registry/discovery.py", line 141, in run
    self.process_category_package(
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/orangecanvas/registry/discovery.py", line 213, in process_category_package
    cat_desc.project_name = distribution.name
  File "/home/denolf/ewokstest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2900, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'name'
``

It seems that the correct attribute is not 'name' but 'project_name' (I tried python 3.9 and 3.11).

**Comment by woutdenolf** [comment]
Seems like there are two places where this can occur:

https://github.com/biolab/orange-canvas-core/blob/124c559535f586b95beaf656aac3a4b811761638/orangecanvas/registry/discovery.py#L352

https://github.com/biolab/orange-canvas-core/blob/124c559535f586b95beaf656aac3a4b811761638/orangecanvas/registry/discovery.py#L372

**Comment by woutdenolf** [comment]
The distribution seems to be of type `pkg_resources.DistInfoDistribution`.

**Comment by woutdenolf** [comment]
Problem seems to be this commit: https://github.com/biolab/orange-canvas-core/commit/488f691d1dbd3dda3c764703a62f96e6be8c4979#diff-8a4d7e657dbf9ce778437786cf1a4cfb7df551c2faf7792be0b7cd65ff191587

Ping @ales-erjavec

**Comment by woutdenolf** [comment]
https://setuptools.pypa.io/en/latest/pkg_resources.html#distribution-attributes (it says `project_name`)

From https://setuptools.pypa.io/en/latest/pkg_resources.html#history

```
0.6a1

    Distribution and Requirement both have a project_name attribute for the project name they refer to. (Previously these were name and distname attributes.)
```

**Comment by woutdenolf** [comment]
When running the tests of this project the distribution variable type is `importlib.metadata.PathDistribution` which does have a `name` attribute.

However this when getting distribution from an entry point (not covered by the unit test) you get distribution variable type `pkg_resources.DistInfoDistribution` which does not have a `name` attribute (called `project_name` instead).

**Comment by woutdenolf** [comment]
In fact the error is in another project: https://gitlab.esrf.fr/workflow/ewoks/ewoksorange/-/blob/main/src/ewoksorange/canvas/config.py?ref_type=heads

Sorry for the noise.

**Comment by markotoplak** [comment]
@woutdenolf, yes, orange-canvas-core 0.2.0 is indeed also incompatible with the current master of Orange (which depended on orange-canvas-core<0.2 for a long time now.

**Comment by markotoplak** [comment]
See https://github.com/biolab/orange3/pull/6655 for more info.
