### ISSUE TITLE
Almost all fonts are bold (Mac + Qt5)

### ISSUE THREAD

**Issue by markotoplak** [biolab/orange-canvas-core#314]
#301 introduces a regression on Macs that use Qt5.

How it used to (and probably should) look like:

![before-fix](https://github.com/user-attachments/assets/f461a2f4-0368-43a4-9a29-e5d7e233a79c)

And how Orange looks after #301. 

![after-fix](https://github.com/user-attachments/assets/9820cc0c-eac7-4780-8983-bcdc632e6178)

I do not get the same issue on Linux.

Thanks to @JakaKokosar for spotting it!

**Comment by wvdvegte** [comment]
I noticed this too, in September, and [asked about it on Discord](https://discord.com/channels/633376992607076354/1284146022666342450/1284146022666342450) - got no reply. Good that it's been picked up now.

**Comment by markotoplak** [comment]
I saw it once too, but thought is was something with my machine... Oh well.
