### ISSUE TITLE
Add-on dialogue: Markdown formatting removed

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange-canvas-core#62]
Add-on dialogue in v 3.23.1
<img width="520" alt="Screen Shot 2019-11-26 at 14 43 12" src="https://user-images.githubusercontent.com/12524972/69638587-4261de80-105b-11ea-936f-1649df11f262.png">

Add-on dialogue on current master
<img width="520" alt="Screen Shot 2019-11-26 at 14 44 40" src="https://user-images.githubusercontent.com/12524972/69638611-4d1c7380-105b-11ea-943c-cb0d52e736f8.png">

Somewhere we have lost markdown formatting. @markotoplak is in favour of removing markdown altogether. I like it, but if no markdown is a better option, I'm fine with it also.

What we need to do is either make the dialogue render as .md or rewrite add-on descriptions to have a nicer format.

**Comment by janezd** [comment]
I like markdown, too. Unless it complicates our lives. Previous version looks nicer.
