### ISSUE TITLE
Workflow text annotation styles

### ISSUE THREAD

**Issue by Hrovatin** [biolab/orange-canvas-core#73]
Currently, there is an option to add text to Orange workflows. However, there is only one size/colour of text. Thus all the annotations seem equally important although when preparing a workflow this is rarely the case. It would be very beneficial if there was an option to change at least size of the text for different annotations and possibly the colour as well. The use of markdown would be an option.

**Comment by ales-erjavec** [comment]
The default text size for a new annotation can be changed via a drop down menu on the button from which the annotation is created (press and hold the button).

The text can be edited and rendered as markdown, rst or html by <kbd>Alt + Right click</kbd> on the created annotation item in the canvas and selecting *Render as* -> ...

**Comment by irgolic** [comment]
I had no idea we had this functionality. Let's make the context menus show up on `Right click`, not press and hold, and `Alt + Right click` respectively.
