### ISSUE TITLE
Raise minimum python from 3.5 -> 3.6?

### ISSUE THREAD

**Issue by irgolic** [biolab/orange-canvas-core#83]
Orange3 and orange-widget-base have both abandoned `python3.5` support, making it impractical to set up a minimum-requirements virtual environment for orange development.

Is there any special reason orange-canvas-core is on 3.5?

**Comment by janezd** [comment]
We discussed this: there seems to be no reason to require 3.6. Do you have any?

**Comment by irgolic** [comment]
Only convenience reasons, it'd bring all three of the main orange repositories to the same minimum requirement, and tests which run locally (in my 3.6 env) would stop failing on Travis (3.5 env).
